name: flutter_formx
description: Flutter FormX provides an easy way of dealing with forms and their states without creating a lot of boilerplate code.
version: 3.0.1
homepage: https://github.com/revelojobs/flutter_formx
repository: https://github.com/revelojobs/flutter_formx
issue_tracker: https://github.com/revelojobs/flutter_formx/issues

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.0
  bloc: ^8.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  flutter_lints: ">=2.0.0 <4.0.0"
  mockito: ^5.4.0
  bloc_test: ^9.1.4
