name: (automatic) PR Verification

on:
  pull_request:
jobs:
  pr-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          cache: true
      - name: Cache pubspec dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: "[Example] Pub get"
        working-directory: ./example
        run: flutter pub get
      - name: "[Example] Build"
        working-directory: ./example
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: "[Example] Linter"
        working-directory: ./example
        run: flutter analyze
      - name: "[Lib] Linter"
        run: flutter analyze
      - name: "[Lib] Test"
        run: flutter test
